/**
 * BlkBox Integration Example
 *
 * Demonstrates how to start the complete system:
 * - Rust FFI honeypots (HTTP, SSH, FTP)
 * - Event pipeline for processing attacks
 * - Management dashboard for visualization
 *
 * Usage:
 *   deno run --allow-all blkbox/example-integration.ts
 */

import { ManagementServer } from "./server/server.ts";
import { createStandardPipeline } from "./server/event-pipeline.ts";
import type { AttackEvent } from "../lib_deno/types.ts";

// Mock FFI for demonstration (replace with actual FFI in production)
const mockFFI = {
    // Initialize BlkBox runtime
    init: () => {
        console.log("[FFI] Initialized BlkBox runtime");
        return { id: 1 };
    },

    // Start a honeypot
    startHoneypot: (type: string, port: number) => {
        console.log(`[FFI] Starting ${type} honeypot on port ${port}`);
        return port;
    },

    // Stop a honeypot
    stopHoneypot: (id: number) => {
        console.log(`[FFI] Stopping honeypot ${id}`);
    },

    // Poll for attack events
    pollEvents: async (): Promise<AttackEvent[]> => {
        // In production, this would call FFI to get events from Rust
        // For demo, return empty (events will be generated by timer below)
        return [];
    }
};

/**
 * Main application
 */
async function main() {
    console.log("🛡️  BlkBox Honeypot System - Starting...\n");

    // 1. Initialize FFI
    console.log("📦 Step 1: Initialize Rust FFI");
    const runtime = mockFFI.init();
    console.log(`   ✓ Runtime ID: ${runtime.id}\n`);

    // 2. Create event pipeline
    console.log("⚙️  Step 2: Create event processing pipeline");
    const pipeline = createStandardPipeline(undefined, {
        logging: { level: "info" },
        rateLimit: { maxRequestsPerMinute: 100 }
    });
    console.log(`   ✓ Processors: ${pipeline.getProcessors().join(", ")}\n`);

    // 3. Start Management Server
    console.log("🌐 Step 3: Start management dashboard");
    const dashboardPort = 8080;
    const server = new ManagementServer({
        port: dashboardPort,
        host: "0.0.0.0",
        enableCors: true,
        maxConnections: 100,
        eventBufferSize: 1000
    });

    server.setEventPipeline(pipeline);
    server.setFFIHandle(runtime);

    await server.start();
    console.log(`   ✓ Dashboard running on http://0.0.0.0:${dashboardPort}\n`);

    // 4. Start Honeypots
    console.log("🍯 Step 4: Start honeypot services");

    const honeypots = [
        { type: "HTTP", port: 8000 },
        { type: "SSH", port: 2222 },
        { type: "FTP", port: 2121 }
    ];

    for (const hp of honeypots) {
        const id = mockFFI.startHoneypot(hp.type, hp.port);
        console.log(`   ✓ ${hp.type} honeypot started (ID: ${id}, Port: ${hp.port})`);
    }

    console.log("\n🎯 System Ready!");
    console.log("━".repeat(60));
    console.log(`📊 Dashboard:     http://localhost:${dashboardPort}/`);
    console.log(`🔌 SSE Stream:    http://localhost:${dashboardPort}/api/events/stream`);
    console.log(`📡 API Health:    http://localhost:${dashboardPort}/api/health`);
    console.log(`📈 Analytics:     http://localhost:${dashboardPort}/api/analytics/summary`);
    console.log("━".repeat(60));
    console.log("\n💡 Honeypots listening:");
    for (const hp of honeypots) {
        console.log(`   • ${hp.type.padEnd(6)} → localhost:${hp.port}`);
    }
    console.log("\n⚡ To simulate attacks, connect to the honeypot ports above");
    console.log("   Example: nc localhost 2121  (for FTP)");
    console.log("            ssh localhost -p 2222  (for SSH)");
    console.log("            curl http://localhost:8000  (for HTTP)\n");

    // 5. Event polling loop
    console.log("🔄 Starting event polling loop...\n");

    // Demo: Generate mock attack events
    startMockAttackGenerator(server, pipeline);

    // In production, poll FFI for real events:
    /*
    setInterval(async () => {
        try {
            const events = await mockFFI.pollEvents();

            for (const event of events) {
                // Process through pipeline
                const context = await pipeline.process(event);

                // Broadcast to dashboard
                server.broadcastEvent(event);
            }
        } catch (error) {
            console.error("Event polling error:", error);
        }
    }, 100); // Poll every 100ms
    */

    // Handle shutdown
    setupShutdownHandlers(server, runtime);
}

/**
 * Generate mock attack events for demonstration
 */
function startMockAttackGenerator(server: ManagementServer, pipeline: any) {
    const services = ["HTTP", "SSH", "FTP"];
    const ips = [
        "192.168.1.100", "10.0.0.50", "172.16.0.25",
        "45.33.32.156", "185.220.101.45", "198.98.57.207"
    ];

    const payloads = [
        "GET /.env HTTP/1.1",
        "USER admin\\r\\nPASS password123",
        "SSH-2.0-OpenSSH_8.2p1",
        "GET /wp-admin HTTP/1.1",
        "SELECT * FROM users WHERE id=1 OR 1=1",
        "RETR /etc/passwd"
    ];

    let counter = 0;

    setInterval(async () => {
        counter++;

        // Generate random attack
        const event: AttackEvent = {
            timestamp: new Date().toISOString(),
            source_ip: ips[Math.floor(Math.random() * ips.length)],
            source_port: 40000 + Math.floor(Math.random() * 10000),
            service_type: services[Math.floor(Math.random() * services.length)],
            service_id: Math.floor(Math.random() * 3) + 1,
            user_agent: Math.random() > 0.5 ? "curl/7.68.0" : undefined,
            payload: payloads[Math.floor(Math.random() * payloads.length)],
            threat_level: Math.floor(Math.random() * 11),
            fingerprint: Math.random() > 0.7 ? `fp_${counter}` : undefined
        };

        // Process through pipeline
        const context = await pipeline.process(event);

        // Broadcast to dashboard
        server.broadcastEvent(event);

    }, 2000 + Math.random() * 3000); // Random interval 2-5 seconds

    console.log("🎭 Mock attack generator started (generating random attacks)");
}

/**
 * Setup graceful shutdown handlers
 */
function setupShutdownHandlers(server: ManagementServer, runtime: any) {
    const shutdown = async () => {
        console.log("\n\n🛑 Shutting down...");

        console.log("   Stopping management server...");
        await server.stop();

        console.log("   Stopping honeypots...");
        // In production: call FFI to stop honeypots

        console.log("   Cleanup complete");
        Deno.exit(0);
    };

    // Handle Ctrl+C
    Deno.addSignalListener("SIGINT", () => {
        shutdown();
    });

    // Handle termination
    Deno.addSignalListener("SIGTERM", () => {
        shutdown();
    });
}

// Run the application
if (import.meta.main) {
    main().catch((error) => {
        console.error("Fatal error:", error);
        Deno.exit(1);
    });
}
